name: Release

on:
  release:
    types: [created]
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get github.com/dmwm/cmsauth
        go get github.com/dmwm/das2go
        go get github.com/vkuznet/x509proxy
        go get github.com/buger/jsonparser
        go get github.com/pkg/profile
        go get github.com/stretchr/testify

    - name: Build
      run: |
        GOARCH=amd64 GOOS=windows go build -ldflags="-s -w -extldflags -static" -o dasgoclient.exe
        GOOS=darwin go build -ldflags="-s -w -extldflags -static" -o dasgoclient_osx
        GOARCH=ppc64le GOOS=linux go build -ldflags="-s -w -extldflags -static" -o dasgoclient_ppc
        GOARCH=arm64 GOOS=linux go build -ldflags="-s -w -extldflags -static" -o dasgoclient_arm
        GOOS=linux go build -ldflags="-s -w -extldflags -static" -o dasgoclient_linux
    - name: Upload binaries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ needs.create_release.outputs.id }}
        args: 'dasgoclient_*'
